<?php

namespace Tests\Support\Parity;

use Viewi\JsTranspile\RestrictedFunctions;

/**
 * Renders FUNCTIONS.md: every PHP function Viewi can run in the browser, with its parity status.
 * Built from functions.php, RestrictedFunctions and the parity cases, so it can not drift:
 * ParityCoverageTest fails when the committed file differs from render(). Write it with
 * `composer functions-doc`.
 */
final class FunctionsDoc
{
    public const PATH = __DIR__ . '/../../../FUNCTIONS.md';

    public static function render(): string
    {
        $functions = ParityRunner::functions();
        $cases = ParityRunner::cases();
        $restricted = RestrictedFunctions::all();
        $known = ParityRunner::knownDifferences();

        // known differences per function: the markers on its cases, plus where a difference says it shows
        $differences = [];
        foreach ($cases as $fn => $list) {
            foreach ($list as $case) {
                if ($case['knownDiff'] !== null) {
                    $differences[$fn][$case['knownDiff']] = true;
                }
            }
        }
        foreach ($known as $id => $difference) {
            foreach ($difference['functions'] as $fn) {
                if (isset($functions[$fn])) {
                    $differences[$fn][$id] = true;
                }
            }
        }

        $groups = [];
        $totals = ['verified' => 0, 'known difference' => 0, 'server-only' => 0, 'internal' => 0];
        foreach ($functions as $fn => $class) {
            $group = explode('\\', $class)[2];
            if (isset($restricted[$fn])) {
                [$kind, $reason] = $restricted[$fn];
                $status = $kind === RestrictedFunctions::SERVER_ONLY ? 'server-only' : 'internal';
                $notes = $reason;
            } elseif (isset($differences[$fn])) {
                $status = 'known difference';
                $ids = array_keys($differences[$fn]);
                sort($ids);
                $notes = implode(', ', array_map(fn($id) => "[$id](#$id)", $ids));
            } else {
                $status = 'verified';
                $notes = '';
            }
            $totals[$status]++;
            $groups[$group][$fn] = [$status, count($cases[$fn] ?? []), $notes];
        }
        ksort($groups);

        $out = "# PHP functions in the browser\n\n"
            . "Generated by `composer functions-doc` from `src/Viewi/JsTranspile/functions.php`, `RestrictedFunctions`\n"
            . "and the parity cases in `tests/Support/Data/parity/`. Do not edit by hand: the test suite fails when\n"
            . "this file is out of date.\n\n"
            . "A Viewi component runs twice: PHP renders it on the server, then the browser runs it again with the\n"
            . "JS port of every PHP function it calls. The parity tests call both with the same arguments and compare\n"
            . "the results, types included, so a page can not render one way on the server and another way after\n"
            . "hydration.\n\n"
            . "- **verified**: every parity case matches PHP.\n"
            . "- **known difference**: matches PHP except for a documented case the browser can not reproduce (below).\n"
            . "- **server-only**: calling it from a component fails the build; the reason is given.\n"
            . "- **internal**: a helper other ports or the transpiler use; not called from a component.\n\n"
            . '**' . count($functions) . ' functions**: ' . $totals['verified'] . ' verified, '
            . $totals['known difference'] . ' with a known difference, ' . $totals['server-only'] . ' server-only, '
            . $totals['internal'] . " internal.\n\n"
            . "## Known differences\n";
        foreach ($known as $id => $difference) {
            $out .= "\n### $id\n\n" . $difference['why'] . "\n\n**Advice:** " . $difference['advice'] . "\n";
        }
        $out .= "\n## Functions\n";
        foreach ($groups as $group => $rows) {
            ksort($rows);
            $out .= "\n### $group\n\n| Function | Status | Cases | Notes |\n|---|---|---|---|\n";
            foreach ($rows as $fn => [$status, $count, $notes]) {
                $out .= "| `$fn` | $status | $count | " . str_replace('|', '\\|', $notes) . " |\n";
            }
        }
        return $out;
    }
}
