export const ReserverProps = {
    _props: true,
    $_callbacks: true,
    _refs: true,
    _slots: true,
    _element: true,
    $$t: true,
    $$r: true,
    $: true,
    $$p: true,
    _name: true,
    emitEvent: true,
    _provides: true,
    _parent: true,
}